name: pokeserver
version: '${project.version}'
main: ppookkjjqq.pokeserver.Pokeserver
api-version: '1.16'
commands:
  moneyup:
    description: a1

  moneyset:
    description: a2

  givemoney:
    description: a3
